before_install:
  - curl -LO https://github.com/sigstore/cosign/releases/download/v2.2.2/cosign-linux-amd64
  - sudo mv cosign-linux-amd64 /usr/local/bin/cosign
  - sudo chmod +x /usr/local/bin/cosign
keys: SSH_KEY_FOR_SIGNING
env:
  secret: “...” # encrypted COSIGN_PASSWORD
before_script: 
  - travis_key SSH_KEY_FOR_SIGNING cosign.key  # cosign requires the key to be in a file
script: 
  - cosign sign --key cosign.key ngnix:latest
