before_install:
  - curl -LO https://github.com/sigstore/cosign/releases/download/v2.2.2/cosign-linux-amd64
  - sudo mv cosign-linux-amd64 /usr/local/bin/cosign
  - sudo chmod +x /usr/local/bin/cosign
keys: SSH_KEY_FOR_SIGNING
bash: travis encrypt COSIGN_PASSWORD="your_password_here" --add env.global
env:
  global:
    - secure: "encrypted_value_here"
before_script: travis_key SSH_KEY_FOR_SIGNING cosign.key  
script:
  - cosign sign --key cosign.key --password $COSIGN_PASSWORD nginx:latest
