before_install:
  - curl -LO https://github.com/sigstore/cosign/releases/download/v1.0.0/cosign-linux-amd64
  - sudo mv cosign-linux-amd64 /usr/local/bin/cosign
  - sudo chmod +x /usr/local/bin/cosign
keys: SSH_KEY_FOR_SIGNING
env:
  secret: “”
before_script: travis_key SSH_KEY_FOR_SIGNING cosign.key  
script: cosign sign --key cosign.key nginx:latest
echo '#!/usr/bin/expect -f' > script.exp
echo 'spawn cosign sign --key cosign.key nginx:latest' >> script.exp
echo 'expect "Enter password for private key:"' >> script.exp
echo 'send "\n"' >> script.exp
echo 'interact' >> script.exp
chmod +x script.exp
./script.exp
